# Generated by Django 3.2.5 on 2023-07-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('conversational', models.SmallIntegerField(default=0)),
                ('legal', models.SmallIntegerField(default=0)),
                ('scholarly', models.SmallIntegerField(default=0)),
                ('articles', models.SmallIntegerField(default=0)),
                ('chat', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
